# Generated by Django 4.2.16 on 2026-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoposition',
            name='venue',
            field=models.CharField(choices=[('LIGHTER', 'Lighter.xyz'), ('HYPERLIQUID', 'Hyperliquid')], default='LIGHTER', max_length=12),
        ),
        migrations.AddIndex(
            model_name='cryptoposition',
            index=models.Index(fields=['status'], name='crypto_cryp_status_521c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoposition',
            index=models.Index(fields=['symbol', 'status'], name='crypto_cryp_symbol_bdcd44_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoposition',
            index=models.Index(fields=['venue', 'status'], name='crypto_cryp_venue_926b05_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoposition',
            index=models.Index(fields=['status', '-opened_at'], name='crypto_cryp_status_94f4da_idx'),
        ),
        migrations.AddConstraint(
            model_name='cryptoposition',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('symbol', 'venue'), name='unique_open_position_per_symbol_venue'),
        ),
    ]
