# Generated by Django 4.2.16 on 2026-03-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0019_drop_polymarket_tables'),
        ('nexus', '0020_tradefeature_llm_fields'),
    ]

    operations = [
    ]
