import os

# Polymarket CLOB API credentials
POLYMARKET_PRIVATE_KEY = os.getenv('POLYMARKET_PRIVATE_KEY', '')
POLYMARKET_API_KEY = os.getenv('POLYMARKET_API_KEY', '')
POLYMARKET_API_SECRET = os.getenv('POLYMARKET_API_SECRET', '')
POLYMARKET_API_PASSPHRASE = os.getenv('POLYMARKET_API_PASSPHRASE', '')
POLYMARKET_CHAIN_ID = int(os.getenv('POLYMARKET_CHAIN_ID', '137'))
POLYMARKET_SIGNATURE_TYPE = int(os.getenv('POLYMARKET_SIGNATURE_TYPE', '0'))

# Trading parameters
KELLY_FRACTION = float(os.getenv('POLYMARKET_KELLY_FRACTION', '0.15'))
EV_THRESHOLD = float(os.getenv('POLYMARKET_EV_THRESHOLD', '0.05'))
MAX_POSITIONS = int(os.getenv('POLYMARKET_MAX_POSITIONS', '5'))
CAPITAL_USD = float(os.getenv('POLYMARKET_CAPITAL_USD', '500'))
MAX_KELLY_BET = 0.25  # cap single bet at 25% of capital
STOP_LOSS_THRESHOLD = -0.15  # exit if position down 15%

# LLM estimation
LLM_MODEL = os.getenv('POLYMARKET_LLM_MODEL', 'claude-haiku-4-5-20251001')
LLM_MAX_MARKETS = int(os.getenv('POLYMARKET_LLM_MAX_MARKETS', '50'))
ESTIMATION_CACHE_MINUTES = 30

# LMSR parameters
LMSR_LIQUIDITY_PARAM = 100.0  # b parameter
