"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os  # Added for environment variables
from celery.schedules import crontab
from dotenv import load_dotenv  # Optional: If using a .env file

# Load environment variables from .env file if present
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%j5tpuhd$lvp23tt+bszj2(xc=b(0o#@h4#r5ty1i5tog8=cmu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [os.getenv('DJANGO_DOMAIN'), 'localhost', '127.0.0.1', 'example.com', 'django']

CSRF_TRUSTED_ORIGINS = [
    f"https://{os.getenv('DJANGO_DOMAIN')}",
    f"http://{os.getenv('DJANGO_DOMAIN')}",
]

# If you need to debug CSRF issues, you can temporarily add:
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_DOMAIN = os.getenv('DJANGO_DOMAIN')
SESSION_COOKIE_SECURE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/quant.log'),
            'formatter': 'verbose',
        },
        'crypto_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/crypto.log'),
            'formatter': 'verbose',
        },
        'lighter_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/lighter.log'),
            'formatter': 'verbose',
        },
        'ai_brain_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/ai_brain.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'app.quant': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'app.crypto': {
            'handlers': ['console', 'crypto_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'app.lighter': {
            'handlers': ['console', 'lighter_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'app.quant.ai_brain': {
            'handlers': ['console', 'ai_brain_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'position_manager': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'celery',
    'django_extensions',
    'app.nexus',
    'app.quant',
    'app.crypto',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this after SecurityMiddleware
    'corsheaders.middleware.CorsMiddleware',  # Added for CORS
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Finnhub API key for Market Pulse news feed
FINNHUB_API_KEY = os.environ.get('FINNHUB_API_KEY', '')

# Redis cache (used by Market Pulse and other cached views)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0').replace('/0', '/1'),
        'OPTIONS': {
            'socket_connect_timeout': 5,
            'socket_timeout': 5,
        },
    }
}

CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # To retain existing behavior
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'quant.tasks.run_quant_trailing_stop_algorithm': {'queue': 'critical'},
    'quant.tasks.run_quant_close_algorithm': {'queue': 'critical'},
    'quant.tasks.run_position_reconciliation': {'queue': 'critical'},
    'quant.tasks.run_quant_entry_algorithm': {'queue': 'critical'},
    'quant.tasks.run_ict_scanner': {'queue': 'analysis'},
    'quant.tasks.run_regime_scan': {'queue': 'analysis'},
    'quant.tasks.run_ai_brain': {'queue': 'analysis'},
    'quant.tasks.run_strategy_orchestrator': {'queue': 'analysis'},
    'quant.tasks.run_strategy_rotation': {'queue': 'analysis'},
    'quant.tasks.run_ml_retrain': {'queue': 'analysis'},
    'quant.tasks.run_llm_retrain': {'queue': 'analysis'},
    'quant.tasks.record_to_graph': {'queue': 'graph'},
    'quant.tasks.run_graph_enrichment': {'queue': 'analysis'},
    'quant.tasks.check_graph_health': {'queue': 'default'},
    'quant.tasks.check_news_sentiment': {'queue': 'default'},
}

# --- Neo4j Knowledge Graph ---
NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://neo4j:7687')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', '')
GRAPH_FEATURES_ACTIVE = os.getenv('GRAPH_FEATURES_ACTIVE', 'false').lower() == 'true'
GRAPH_FEATURES_LIVE_FALLBACK = False
GRAPH_ROUTER_SIGNAL_ACTIVE = os.getenv('GRAPH_ROUTER_SIGNAL_ACTIVE', 'false').lower() == 'true'
CELERY_BEAT_SCHEDULE = {
    'run-quant-entry-algorithm': {
        'task': 'quant.tasks.run_quant_entry_algorithm',  # This should match the @shared_task name
        'schedule': 60.0 * 1,
    },
    'run-quant-trailing-stop-algorithm': {
        'task': 'quant.tasks.run_quant_trailing_stop_algorithm',  # This should match the @shared_task name
        'schedule': 2,  # every 2 seconds — gold/silver can move $10+ in 5s
    },
    'run-quant-close-algorithm': {
        'task': 'quant.tasks.run_quant_close_algorithm',  # This should match the @shared_task name
        'schedule': 15,
    },
    'run-position-reconciliation': {
        'task': 'quant.tasks.run_position_reconciliation',
        'schedule': 30,  # every 30s — catches MT5↔DB desync from crashes/timeouts
    },
    'run-backtest': {
        'task': 'quant.tasks.run_backtest',
        'schedule': 60.0 * 60 * 6,  # every 6 hours
    },
    # --- Hyperliquid: re-enabled alongside Lighter for multi-venue ---
    'sync-crypto-prices': {
        'task': 'crypto.tasks.sync_crypto_prices',
        'schedule': 60.0,
    },
    'run-crypto-entry': {
        'task': 'crypto.tasks.run_crypto_entry',
        'schedule': 60.0,
    },
    'run-crypto-exit': {
        'task': 'crypto.tasks.run_crypto_exit',
        'schedule': 30.0,
    },
    # --- Lighter.xyz DEX (zero-fee venue) ---
    'run-lighter-entry': {
        'task': 'crypto.tasks.run_lighter_entry',
        'schedule': 60.0,  # EMA trend-following — 1min (signals on 15m/1h candles, no rush)
    },
    'run-lighter-reconcile': {
        'task': 'crypto.tasks.run_lighter_reconcile',
        'schedule': 60.0,  # Sync DB — 1min
    },
    'run-lighter-exit': {
        'task': 'crypto.tasks.run_lighter_exit',
        'schedule': 30.0,  # Exit checks — 30s (most time-sensitive, but on-chain SL/TP covers gaps)
    },
    'run-lighter-grid': {
        'task': 'crypto.tasks.run_lighter_grid',
        'schedule': 60.0,  # Grid refresh — 1min
    },
    'run-lighter-mean-reversion': {
        'task': 'crypto.tasks.run_lighter_mean_reversion',
        'schedule': 45.0,  # MR scan — 45s (15m candle signals, 45s is fine)
    },
    'run-lighter-rsi-scalper': {
        'task': 'crypto.tasks.run_lighter_rsi_scalper',
        'schedule': 30.0,  # RSI(2) scalper — 30s (5m candle signals)
    },
    # --- Funding Rate Arbitrage Monitor (Hyperliquid vs Lighter) ---
    'run-funding-arb-scan': {
        'task': 'crypto.tasks.run_funding_arb_scan',
        'schedule': 300.0,  # every 5 minutes
    },
    # --- LLM-powered tasks DISABLED: $10/day API cost not justified at current scale ---
    # Re-enable when account is consistently profitable. These are "nice to have"
    # on top of the 6 rule-based layers (circuit breaker, symbol filter, regime,
    # group tendency, ML meta-filter, event guard) which cost $0.
    #
    # 'run-macro-analysis': {
    #     'task': 'quant.tasks.run_macro_analysis',
    #     'schedule': 60.0 * 30,  # every 30 minutes
    # },
    # 'run-strategy-evolution': {
    #     'task': 'quant.tasks.run_strategy_evolution',
    #     'schedule': 60.0 * 60 * 6,  # every 6 hours
    # },
    # 'run-ai-brain': {
    #     'task': 'quant.tasks.run_ai_brain',
    #     'schedule': 60.0 * 5,  # every 5 minutes
    # },
    'fetch-market-pulse': {
        'task': 'quant.tasks.fetch_market_pulse',
        'schedule': 120.0,  # every 2 minutes
    },
    'run-regime-scan': {
        'task': 'quant.tasks.run_regime_scan',
        'schedule': 300.0,  # every 5 minutes
    },
    # 'run-ai-brain-executor': {
    #     'task': 'quant.tasks.run_ai_brain_executor',
    #     'schedule': 300.0,  # every 5 minutes
    # },
    'run-ml-retrain': {
        'task': 'quant.tasks.run_ml_retrain',
        'schedule': 60.0 * 30,  # every 30 minutes
    },
    # 'run-llm-retrain': {
    #     'task': 'quant.tasks.run_llm_retrain',
    #     'schedule': crontab(hour=3, minute=0),  # daily at 03:00 UTC (off-market hours)
    # },
    'run-ict-scanner': {
        'task': 'quant.tasks.run_ict_scanner',
        'schedule': 60.0,  # every 1 minute — same as CVD entry
    },
    'check-tick-consumer-health': {
        'task': 'quant.tasks.check_tick_consumer_health',
        'schedule': 60.0,  # every 1 minute
    },
    'check-graph-health': {
        'task': 'quant.tasks.check_graph_health',
        'schedule': 300.0,  # every 5 minutes
    },
    'check-news-sentiment': {
        'task': 'quant.tasks.check_news_sentiment',
        'schedule': 300.0,  # every 5 minutes — free RSS feeds, no API key needed
    },
    'run-strategy-orchestrator': {
        'task': 'quant.tasks.run_strategy_orchestrator',
        'schedule': 300.0,  # every 5 minutes
    },
    # --- Strategy Auto-Rotator (5x daily at session boundaries, weekdays only) ---
    'run-rotation-asia-open': {
        'task': 'quant.tasks.run_strategy_rotation',
        'schedule': crontab(hour=6, minute=0, day_of_week='1-5'),
        'args': ('ASIA_OPEN',),
    },
    'run-rotation-london-open': {
        'task': 'quant.tasks.run_strategy_rotation',
        'schedule': crontab(hour=9, minute=0, day_of_week='1-5'),
        'args': ('LONDON_OPEN',),
    },
    'run-rotation-ny-open': {
        'task': 'quant.tasks.run_strategy_rotation',
        'schedule': crontab(hour=13, minute=0, day_of_week='1-5'),
        'args': ('NY_OPEN',),
    },
    'run-rotation-ny-afternoon': {
        'task': 'quant.tasks.run_strategy_rotation',
        'schedule': crontab(hour=17, minute=0, day_of_week='1-5'),
        'args': ('NY_AFTERNOON',),
    },
    'run-rotation-asia-close': {
        'task': 'quant.tasks.run_strategy_rotation',
        'schedule': crontab(hour=22, minute=0, day_of_week='1-5'),
        'args': ('ASIA_CLOSE',),
    },
}